name = "Orihime"
uuid = "377fe491-a7cd-4fe2-889a-b15ed48b0c90"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
